""" 
This is a utility that plots the instances for each class in the validation dataset similar to the instances graph for the test dataset generated by ultralytics after a training run.
The class names are copied from the data.yaml file.

This was generated by ChatGPT. The width and spacing between bars was manually adjusted to more closely resemble the graph generated by the ultrlytics module.
"""

from pathlib import Path
from collections import Counter
import matplotlib.pyplot as plt
import numpy as np
from config import *

LABEL_DIR = VAL_DATA_DIR / "labels"

counts = Counter()

# Count instances
for txt_file in LABEL_DIR.glob("*.txt"):

    with open(txt_file, "r") as f:
        lines = f.readlines()

    for line in lines:

        parts = line.strip().split()

        if len(parts) < 5:
            continue

        cls = int(parts[0])
        counts[cls] += 1

# Prepare plot data
class_ids = sorted(CLASS_NAMES.keys())
labels = [CLASS_NAMES[i] for i in class_ids]
values = [counts[i] for i in class_ids]
colors = [CLASS_COLORS[i] for i in class_ids]

# tighter spacing between bars
x = np.array([0,1,2,3,4,5,6,7,8,9,10,11]) * 0.18

# Figure
fig, ax = plt.subplots(figsize=(7, 7))

bars = ax.bar(
    x,
    values,
    width=0.15,          # skinnier bars
    color=colors,
    edgecolor="none"
)

# Value labels above bars
for bar, value in zip(bars, values):

    ax.text(
        bar.get_x() + bar.get_width() / 2,
        value,
        str(value),
        ha="center",
        va="bottom",
        fontsize=12
    )

# Labels
ax.set_ylabel("instances", fontsize=14)

ax.set_xticks(x)
ax.set_xticklabels(labels, rotation=90, fontsize=12)

# Remove axis lines only
for spine in ax.spines.values():
    spine.set_visible(False)

# Keep tick marks
ax.tick_params(axis='x', bottom=True, length=4)
ax.tick_params(axis='y', left=True, length=4)

plt.tight_layout()
plt.show()