"""
Author: Yuvraj Fagotra
Date: 16/04/2026

ChatGPT was used to fix syntax errors and generate boilerplate where needed. Any generated code was used only as reference and edited, refactored, and structured manually unless stated otherwise. 
"""

from ultralytics import YOLO
from pathlib import Path
import shutil

MODELS_DIR_NAME = "models"

def get_model_name_from_user():
    user_input = input("Enter YOLO model name: ")
    return user_input if user_input.endswith(".pt") else user_input + ".pt"

def load_model(model_name):
    # These four lines were generated by chatGPT
    FILE_DIR = Path(__file__).resolve().parent
    ROOT_DIR = FILE_DIR.parent
    MODELS_DIR = ROOT_DIR / MODELS_DIR_NAME
    MODELS_DIR.mkdir(exist_ok=True)

    local_path = MODELS_DIR / model_name
    try:
        print(f"[INFO] Loading {model_name}...")
        model = YOLO(str(local_path)) 
        print(f"[INFO] {model_name} saved to {local_path}")
        return model
            
    except Exception as e:
        print(f"ERR: Could not load model {model_name}")
        print(e)
    
def load_model_from_user_input():
    model = None
    while model is None:
        model_name = get_model_name_from_user()
        model = load_model(model_name)
    return model

if __name__ == "__main__":
    load_model_from_user_input()