def hex_to_bgr(hex_color):
    """
    Generated by ChatGPT
    """
    if hex_color == None:
        return (0, 0, 0)

    return tuple(
        int(hex_color[i:i+2], 16)
        for i in (5, 3, 1)
    )